# Q1. Write a code to create a 4X3 matrix with values ranging from 2 to 13.

In [2]:
import numpy as np

In [3]:
arr=np.arange(2,14).reshape(4,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

# Q2. Write a code to replace the odd numbers by -1 in the array created by using random.randint(1,50,20)

In [4]:
arr1=np.random.randint(1,50,20)

In [5]:
arr1

array([14, 28, 47,  5, 10, 19, 14,  4,  1, 42, 20, 36, 26,  8, 17,  8, 11,
       13, 35, 26], dtype=int32)

In [6]:
arr1[arr1%2!=0]=-1

In [7]:
arr1

array([14, 28, -1, -1, 10, -1, 14,  4, -1, 42, 20, 36, 26,  8, -1,  8, -1,
       -1, -1, 26], dtype=int32)

# Q3.Perform the following operations on an array of mobile phones prices 6999,7500,11299,27899,14999,9999. 

In [9]:
arr2=np.array([6999,7500,11299,27899,14999,9999])

In [10]:
arr2

array([ 6999,  7500, 11299, 27899, 14999,  9999])

In [11]:
arr2=arr2.astype(float)

In [12]:
arr2

array([ 6999.,  7500., 11299., 27899., 14999.,  9999.])

In [16]:
arr2=np.append(arr2,13999)
arr2

array([ 6999.,  7500., 11299., 27899., 14999.,  9999., 13999., 13999.])

In [17]:
reverse=arr2[::-1]

In [18]:
reverse

array([13999., 13999.,  9999., 14999., 27899., 11299.,  7500.,  6999.])

In [22]:
arr=arr2*1.18
arr

array([ 8258.82,  8850.  , 13332.82, 32920.82, 17698.82, 11798.82,
       16518.82, 16518.82])

In [24]:
arr=np.sort(arr)[::-1]

In [25]:
arr

array([32920.82, 17698.82, 16518.82, 16518.82, 13332.82, 11798.82,
        8850.  ,  8258.82])

In [26]:
arr.mean()

np.float64(15737.217499999999)

In [28]:
max=arr.max()

In [29]:
min=arr.min()

In [30]:
diff=max-min

In [31]:
diff

np.float64(24662.0)

# Q4. Find out the indices of non zero element in given array[1,2,0,0,4,0]

In [32]:
arr=np.array([1,2,0,0,4,0])

In [33]:
arr=np.nonzero(arr)
arr

(array([0, 1, 4]),)