# Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [1]:
import numpy as np

In [2]:
arr=np.arange(2,14).reshape(4,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

# Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [3]:
arr1=np.random.randint(1,50,20)
arr1[arr1%2!=0]=-1

In [4]:
arr1

array([ 8, 42, 16, -1,  4, 36, -1, 18, -1, 26, 18, 32, -1, -1, -1, -1,  6,
       24, -1, 44], dtype=int32)

# Perform the following operations on an array of mobile phones prices 6999, 7500 , 11299 , 27899 , 14999 , 9999

### a. Create a 1d-array of mobile phones prices

In [6]:
arr=np.array([6999,7500,11299,27899,14999,9999])
arr

array([ 6999,  7500, 11299, 27899, 14999,  9999])

### b. Convert this array to float type

In [10]:
arr.astype(float)

array([ 6999.,  7500., 11299., 27899., 14999.,  9999.])

### c. Append a new mobile having price of 13999 Rs. to this array

In [21]:
arr=np.append(arr,13999)
arr

array([ 6999,  7500, 11299, 27899, 14999,  9999, 13999])

### d. Reverse this array of mobile phones prices

In [22]:
arr[::-1]

array([13999,  9999, 14999, 27899, 11299,  7500,  6999])

### e. Apply GST of 18% on mobile phones prices and update this array.

In [29]:
arr=arr+((arr*18)/100)
arr

array([38846.5676, 20884.6076, 19492.2076, 15732.7276, 13922.6076,
       10443.    ,  9745.4076])

### f. Sort the array in descending order of price

In [30]:
arr.sort(descending=1)

In [31]:
arr

array([38846.5676, 20884.6076, 19492.2076, 15732.7276, 13922.6076,
       10443.    ,  9745.4076])

### g. What is the average mobile phone price

In [32]:
arr.mean()

np.float64(18438.1608)

### h. What is the difference b/w maximum and minimum price

In [33]:
difference=arr.max()-arr.min()

In [34]:
difference

np.float64(29101.160000000003)

# Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [36]:
arr1=np.array([1,2,0,0,4,0])
np.nonzero(arr1)

(array([0, 1, 4]),)