## 1. Create a NumPy array containing integers from 0 to 9.

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
list1=[10,20,30,40,50]
arr=np.array(list1)
arr

array([10, 20, 30, 40, 50])

## 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [4]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4.  Given a 2D array, find its shape and size.


In [5]:
arr.shape

(3, 3)

In [6]:
arr.size

9

## Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [7]:
arr2=np.random.randint(1,100,20).reshape(5,4)

In [8]:
arr2.shape

(5, 4)

In [9]:
arr2.size

20

## 5. Create a 3x3 array of integers and access:
### a. The second element of the first row.
### b. The third column of the 2nd row.
### c. A subarray with the first two rows and last two columns.

In [10]:
arr=np.arange(1,10).reshape(3,3)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# The second element of the first row.
arr[0,1]

np.int64(2)

In [13]:
# The third column of the 2nd row
arr[1,2]

np.int64(6)

In [14]:
# A subarray with the first two rows and last two columns.
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

## 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [15]:
arr=np.random.randint(1,50,12)

In [16]:
arr

array([ 9, 28, 42, 33, 36, 45, 39, 15, 15,  9, 28,  3], dtype=int32)

In [17]:
arr=arr.reshape(3,4)

In [18]:
arr

array([[ 9, 28, 42, 33],
       [36, 45, 39, 15],
       [15,  9, 28,  3]], dtype=int32)

## 7. Reshape a 3x3 matrix into a 1D array.

In [21]:
arr=np.arange(1,10).reshape(3,3)

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr=arr.reshape(1,9)

In [25]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
arr=arr.reshape(9)

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [29]:
arr1=np.arange(1,7).reshape(2,3)

In [35]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2=np.arange(7,13).reshape(2,3)

In [39]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
# Addition
result=arr1+arr2
result

array([[ 8, 10, 12],
       [14, 16, 18]])

In [41]:
# Subtraction
result=arr1-arr2
result

array([[-6, -6, -6],
       [-6, -6, -6]])

In [42]:
# Multiplication
result=arr1*arr2
result

array([[ 7, 16, 27],
       [40, 55, 72]])

In [43]:
# Division
result=arr1/arr2
result

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

## 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [44]:
arr=np.random.randint(1,50,20)

In [45]:
arr

array([37,  6,  8, 26,  7,  5, 36, 49, 31,  7, 35,  1, 15, 16, 31,  9, 19,
        8,  7, 40], dtype=int32)

In [46]:
arr.sum()

np.int64(393)

In [47]:
arr.mean()

np.float64(19.65)

In [48]:
arr.std()

np.float64(14.188992212274979)

## 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.


In [49]:
A=np.random.randint(1,50,4).reshape(2,2)
B=np.random.randint(1,50,4).reshape(2,2)

In [50]:
A

array([[45, 11],
       [ 6, 27]], dtype=int32)

In [51]:
B

array([[25, 20],
       [21, 26]], dtype=int32)

In [52]:
result=np.dot(A,B)

In [53]:
result

array([[1356, 1186],
       [ 717,  822]], dtype=int32)

In [54]:
result=A@B

In [55]:
result

array([[1356, 1186],
       [ 717,  822]], dtype=int32)

## 11. Find the transpose of matrix A and matrix B.

In [57]:
transpose_A=A.T

In [59]:
transpose_A

array([[45,  6],
       [11, 27]], dtype=int32)

In [61]:
transpose_B=B.T

In [62]:
transpose_B

array([[25, 21],
       [20, 26]], dtype=int32)

## 12. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [65]:
arr=np.random.randint(1,50,16).reshape(4,4)

In [66]:
arr

array([[19, 42, 41, 45],
       [ 8, 21, 15, 29],
       [ 8, 10, 44, 36],
       [ 8, 30, 12, 34]], dtype=int32)

In [67]:
arr.max()

np.int32(45)

In [68]:
arr.min()

np.int32(8)

In [69]:
arr.mean()

np.float64(25.125)

## 13. Find the row-wise and column-wise sums.

In [72]:
result=np.sum(arr,axis=1)

In [73]:
result

array([147,  73,  98,  84])

In [74]:
result=np.sum(arr,axis=0)

In [75]:
result

array([ 43, 103, 112, 144])

## 14. Generate an array of 10 random integers between 1 and 50.

In [76]:
arr=np.random.randint(1,50,10)

In [77]:
arr

array([ 1, 22, 47, 16, 34, 44,  2, 30, 13, 18], dtype=int32)